name: CI

on: 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup V
              uses: vlang/setup-v@v1.4
              with:
                version: 'weekly.2025.21'
            - name: Run tests
              run: v test .
